[env]
RUST_MIN_STACK = "33554432"
LIBSQLITE3_SYS_USE_PKG_CONFIG = "0"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
rustflags = [
  "-C",
  "linker=rust-lld",
  "-C",
  "codegen-units=256",
  "-C",
  "debuginfo=line-tables-only",
  "-C",
  "split-debuginfo=packed",
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
