import {
  Activity, BookHeart, Bot, Brain, ClipboardList, Clock4, Droplets,
  FileText, Gauge, Hourglass, LayoutDashboard, LayoutGrid, Library,
  Mic, Moon, Settings, ShieldCheck, ShoppingCart, SmilePlus, Target,
  Timer, Trophy, UtensilsCrossed, Wallet, Wind,
  Plus, Calendar, CheckCircle, Flame, BarChart, Edit, History,
  MinusCircle, PieChart, Heart,
  Utensils, Smile, Flag, TrendingUp, Search, Clock,
  FilePlus, MessageSquare, X, ChevronDown,
} from 'lucide-svelte';
import type { ComponentType } from 'svelte';

const iconRegistry: Record<string, ComponentType> = {
  activity: Activity,
  'book-heart': BookHeart,
  bot: Bot,
  brain: Brain,
  'clipboard-list': ClipboardList,
  'clock-4': Clock4,
  droplets: Droplets,
  'file-text': FileText,
  gauge: Gauge,
  hourglass: Hourglass,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  library: Library,
  mic: Mic,
  moon: Moon,
  settings: Settings,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  'smile-plus': SmilePlus,
  target: Target,
  timer: Timer,
  trophy: Trophy,
  'utensils-crossed': UtensilsCrossed,
  wallet: Wallet,
  wind: Wind,
  plus: Plus,
  calendar: Calendar,
  'check-circle': CheckCircle,
  flame: Flame,
  'bar-chart': BarChart,
  edit: Edit,
  history: History,
  'minus-circle': MinusCircle,
  'pie-chart': PieChart,
  heart: Heart,
  utensils: Utensils,
  smile: Smile,
  flag: Flag,
  'trending-up': TrendingUp,
  search: Search,
  clock: Clock,
  'file-plus': FilePlus,
  'message-square': MessageSquare,
  x: X,
  'chevron-down': ChevronDown,
};

export function getIcon(name: string): ComponentType {
  return iconRegistry[name] ?? LayoutGrid;
}
